package com.telefonica.workshop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Servicio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("esOnline")
	private java.lang.Boolean esOnline;
	@org.kie.api.definition.type.Label("esVigente")
	private java.lang.Boolean esVigente;
	@org.kie.api.definition.type.Label("ds")
	private java.lang.String ds;
	@org.kie.api.definition.type.Label("ms")
	private java.lang.String ms;
	@org.kie.api.definition.type.Label("equipo")
	private java.lang.String equipo;
	@org.kie.api.definition.type.Label("ciudad")
	private java.lang.String ciudad;
	@org.kie.api.definition.type.Label("direccion")
	private java.lang.String direccion;
	@org.kie.api.definition.type.Label("tipoProducto")
	private java.lang.String tipoProducto;
	@org.kie.api.definition.type.Label("tipoServicio")
	private java.lang.String tipoServicio;
	@org.kie.api.definition.type.Label("esUnAlta")
	private java.lang.Boolean esUnAlta;
	@org.kie.api.definition.type.Label("banwidth")
	private java.lang.Double banwidth;
	@org.kie.api.definition.type.Label("valorProyecto")
	private java.lang.Double valorProyecto;
	@org.kie.api.definition.type.Label("recursosDisponibles")
	private java.lang.Boolean recursosDisponibles;
	@org.kie.api.definition.type.Label("disponibildadEquipos")
	private java.lang.Boolean disponibildadEquipos;
	@org.kie.api.definition.type.Label("disponibildadEquiposSAP")
	private java.lang.Boolean disponibildadEquiposSAP;
	@org.kie.api.definition.type.Label("construccionUK")
	private java.lang.Boolean construccionUK;
	@org.kie.api.definition.type.Label("viabilidadUK")
	private java.lang.Boolean viabilidadUK;
	@org.kie.api.definition.type.Label("presupuestoAprobado")
	private java.lang.Boolean presupuestoAprobado;
	@org.kie.api.definition.type.Label("mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label("ordenTrabajo")
	private java.lang.Boolean ordenTrabajo;
	@org.kie.api.definition.type.Label("instalarEquiposMovistar")
	private java.lang.Boolean instalarEquiposMovistar;

	public Servicio() {
	}

	public java.lang.Boolean getEsOnline() {
		return this.esOnline;
	}

	public void setEsOnline(java.lang.Boolean esOnline) {
		this.esOnline = esOnline;
	}

	public java.lang.Boolean getEsVigente() {
		return this.esVigente;
	}

	public void setEsVigente(java.lang.Boolean esVigente) {
		this.esVigente = esVigente;
	}

	public java.lang.String getDs() {
		return this.ds;
	}

	public void setDs(java.lang.String ds) {
		this.ds = ds;
	}

	public java.lang.String getMs() {
		return this.ms;
	}

	public void setMs(java.lang.String ms) {
		this.ms = ms;
	}

	public java.lang.String getEquipo() {
		return this.equipo;
	}

	public void setEquipo(java.lang.String equipo) {
		this.equipo = equipo;
	}

	public java.lang.String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(java.lang.String ciudad) {
		this.ciudad = ciudad;
	}

	public java.lang.String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(java.lang.String direccion) {
		this.direccion = direccion;
	}

	public java.lang.String getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(java.lang.String tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	public java.lang.String getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(java.lang.String tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	public java.lang.Boolean getEsUnAlta() {
		return this.esUnAlta;
	}

	public void setEsUnAlta(java.lang.Boolean esUnAlta) {
		this.esUnAlta = esUnAlta;
	}

	public java.lang.Double getBanwidth() {
		return this.banwidth;
	}

	public void setBanwidth(java.lang.Double banwidth) {
		this.banwidth = banwidth;
	}

	public java.lang.Double getValorProyecto() {
		return this.valorProyecto;
	}

	public void setValorProyecto(java.lang.Double valorProyecto) {
		this.valorProyecto = valorProyecto;
	}

	public java.lang.Boolean getRecursosDisponibles() {
		return this.recursosDisponibles;
	}

	public void setRecursosDisponibles(java.lang.Boolean recursosDisponibles) {
		this.recursosDisponibles = recursosDisponibles;
	}

	public java.lang.Boolean getDisponibildadEquipos() {
		return this.disponibildadEquipos;
	}

	public void setDisponibildadEquipos(java.lang.Boolean disponibildadEquipos) {
		this.disponibildadEquipos = disponibildadEquipos;
	}

	public java.lang.Boolean getDisponibildadEquiposSAP() {
		return this.disponibildadEquiposSAP;
	}

	public void setDisponibildadEquiposSAP(
			java.lang.Boolean disponibildadEquiposSAP) {
		this.disponibildadEquiposSAP = disponibildadEquiposSAP;
	}

	public java.lang.Boolean getConstruccionUK() {
		return this.construccionUK;
	}

	public void setConstruccionUK(java.lang.Boolean construccionUK) {
		this.construccionUK = construccionUK;
	}

	public java.lang.Boolean getViabilidadUK() {
		return this.viabilidadUK;
	}

	public void setViabilidadUK(java.lang.Boolean viabilidadUK) {
		this.viabilidadUK = viabilidadUK;
	}

	public java.lang.Boolean getPresupuestoAprobado() {
		return this.presupuestoAprobado;
	}

	public void setPresupuestoAprobado(java.lang.Boolean presupuestoAprobado) {
		this.presupuestoAprobado = presupuestoAprobado;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.Boolean getOrdenTrabajo() {
		return this.ordenTrabajo;
	}

	public void setOrdenTrabajo(java.lang.Boolean ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public java.lang.Boolean getInstalarEquiposMovistar() {
		return this.instalarEquiposMovistar;
	}

	public void setInstalarEquiposMovistar(
			java.lang.Boolean instalarEquiposMovistar) {
		this.instalarEquiposMovistar = instalarEquiposMovistar;
	}

	public String toString() {
		return "Metodo toString " + this.esOnline + this.esVigente
				+ this.equipo + this.ms + this.ds + this.ciudad
				+ this.direccion + this.esUnAlta + this.banwidth;
	}

	public Servicio(java.lang.Boolean esOnline, java.lang.Boolean esVigente,
			java.lang.String ds, java.lang.String ms, java.lang.String equipo,
			java.lang.String ciudad, java.lang.String direccion,
			java.lang.String tipoProducto, java.lang.String tipoServicio,
			java.lang.Boolean esUnAlta, java.lang.Double banwidth,
			java.lang.Double valorProyecto,
			java.lang.Boolean recursosDisponibles,
			java.lang.Boolean disponibildadEquipos,
			java.lang.Boolean disponibildadEquiposSAP,
			java.lang.Boolean construccionUK, java.lang.Boolean viabilidadUK,
			java.lang.Boolean presupuestoAprobado, java.lang.String mensaje,
			java.lang.Boolean ordenTrabajo,
			java.lang.Boolean instalarEquiposMovistar) {
		this.esOnline = esOnline;
		this.esVigente = esVigente;
		this.ds = ds;
		this.ms = ms;
		this.equipo = equipo;
		this.ciudad = ciudad;
		this.direccion = direccion;
		this.tipoProducto = tipoProducto;
		this.tipoServicio = tipoServicio;
		this.esUnAlta = esUnAlta;
		this.banwidth = banwidth;
		this.valorProyecto = valorProyecto;
		this.recursosDisponibles = recursosDisponibles;
		this.disponibildadEquipos = disponibildadEquipos;
		this.disponibildadEquiposSAP = disponibildadEquiposSAP;
		this.construccionUK = construccionUK;
		this.viabilidadUK = viabilidadUK;
		this.presupuestoAprobado = presupuestoAprobado;
		this.mensaje = mensaje;
		this.ordenTrabajo = ordenTrabajo;
		this.instalarEquiposMovistar = instalarEquiposMovistar;
	}

}